### ISSUE TITLE
Add Environment support

### ISSUE THREAD

**Issue by ChrisMcKenzie** [ChrisMcKenzie/dropship#1]
Github API can optionally send a deployment environment it would be nice to be able to define a different set of servers for each environment.

maybe something like this:
```yaml
servers:
  development:
    provider: list
    options:
      list:
          -
            address: 127.0.0.1
```

@ericgreene || @krisbarrett || @mattwarren1234  do you have any input?
