### ISSUE TITLE
Mult-task definitions

### ISSUE THREAD

**Issue by ChrisMcKenzie** [ChrisMcKenzie/dropship#2]
I would like to be able to define custom tasks in my `dropship.yml` for example a task that migrates database schemas as well as a task that just deploys the app

__Example:__
```yaml
tasks:
  "deploy:migrate":
      steps:
         - ...
  deploy:
      steps:
        - ...
```
